#!/bin/bash

function update {
  if command -v apt &> /dev/null; then
    sudo apt update
  elif command -v pacman &> /dev/null; then
    sudo pacman -Syu
  fi
}

function install {
  if command -v apt &> /dev/null; then
    sudo apt -y install $1
  elif command -v pacman &> /dev/null; then
    sudo pacman --noconfirm -S $1
  fi
}

# Make sure everything is up-to-date
update

# Install GNU Stow
install stow

# Link dotfiles
stow vim
stow zsh
stow sway

# Install VIM
install vim

# Install zsh
install zsh

# Switch default shell
chsh -s $(which zsh)

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install VIM plugins
vim +PluginInstall +qall
